from cmg import evaluator
from datapreparation import context_generator, example_generator
from runners.cmgrunners import CmgRunner
from runners.contextgeneratorrunners import ContextGeneratorRunner
from runners.examplegeneratorrunners import ExampleGeneratorRunner
from runners.gethighlevelcontextrunners import GetHighLevelContextRunner

context_generator_runner = ContextGeneratorRunner(context_generator)
cmg_runner = CmgRunner(evaluator)
get_high_level_context_runner = GetHighLevelContextRunner(evaluator)
example_generator_runner = ExampleGeneratorRunner(example_generator)
